// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcx4ub92WIb-KAzLh1aIsdJ4hBbWaK46w',
    appId: '1:650755857824:web:aabfb2793f0daeee2698c5',
    messagingSenderId: '650755857824',
    projectId: 'clientprotal-a656c',
    authDomain: 'clientprotal-a656c.firebaseapp.com',
    storageBucket: 'clientprotal-a656c.appspot.com',
    measurementId: 'G-EYRK60Y95S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJmIwhD3HYNCR8mFUPkSgy21lalYAjGjY',
    appId: '1:650755857824:android:b6acf17f3a623cc12698c5',
    messagingSenderId: '650755857824',
    projectId: 'clientprotal-a656c',
    storageBucket: 'clientprotal-a656c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgbrTkrk4fS5btYdjKm357uzHF8oK92UQ',
    appId: '1:650755857824:ios:e826524dd1521cfc2698c5',
    messagingSenderId: '650755857824',
    projectId: 'clientprotal-a656c',
    storageBucket: 'clientprotal-a656c.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgbrTkrk4fS5btYdjKm357uzHF8oK92UQ',
    appId: '1:650755857824:ios:e826524dd1521cfc2698c5',
    messagingSenderId: '650755857824',
    projectId: 'clientprotal-a656c',
    storageBucket: 'clientprotal-a656c.appspot.com',
    iosBundleId: 'com.example.admin',
  );
}
